"""estrutura semanas treino

Revision ID: 6bb0beb3a5f6
Revises: 
Create Date: 2026-05-14 16:09:03.833299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb0beb3a5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cref', sa.String(length=40), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('is_active_flag', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_arquivo', sa.String(length=60), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progresso', sa.Integer(), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('erros_detectados', sa.Text(), nullable=True),
    sa.Column('sugestoes', sa.Text(), nullable=True),
    sa.Column('relatorio_tecnico', sa.Text(), nullable=True),
    sa.Column('codigo_corrigido', sa.Text(), nullable=True),
    sa.Column('metricas', sa.Text(), nullable=True),
    sa.Column('score_seguranca', sa.Integer(), nullable=True),
    sa.Column('score_performance', sa.Integer(), nullable=True),
    sa.Column('score_arquitetura', sa.Integer(), nullable=True),
    sa.Column('score_responsividade', sa.Integer(), nullable=True),
    sa.Column('score_banco', sa.Integer(), nullable=True),
    sa.Column('erro_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('peso_inicial', sa.Float(), nullable=True),
    sa.Column('objetivo', sa.String(length=120), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('condicoes_especiais', sa.String(length=255), nullable=True),
    sa.Column('nivel_condicionamento', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_user_id'), ['user_id'], unique=False)

    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entries_created_at'), ['created_at'], unique=False)

    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('protocolo', sa.String(length=60), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('cintura', sa.Float(), nullable=True),
    sa.Column('quadril', sa.Float(), nullable=True),
    sa.Column('peito', sa.Float(), nullable=True),
    sa.Column('braco', sa.Float(), nullable=True),
    sa.Column('coxa', sa.Float(), nullable=True),
    sa.Column('panturrilha', sa.Float(), nullable=True),
    sa.Column('abdomen', sa.Float(), nullable=True),
    sa.Column('dobra_triceps', sa.Float(), nullable=True),
    sa.Column('dobra_peitoral', sa.Float(), nullable=True),
    sa.Column('dobra_subaxilar', sa.Float(), nullable=True),
    sa.Column('dobra_subescapular', sa.Float(), nullable=True),
    sa.Column('dobra_abdominal', sa.Float(), nullable=True),
    sa.Column('dobra_suprailiaca', sa.Float(), nullable=True),
    sa.Column('dobra_coxa', sa.Float(), nullable=True),
    sa.Column('percentual_gordura', sa.Float(), nullable=True),
    sa.Column('massa_magra', sa.Float(), nullable=True),
    sa.Column('massa_gorda', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('rcq', sa.Float(), nullable=True),
    sa.Column('tmb', sa.Float(), nullable=True),
    sa.Column('classificacao_imc', sa.String(length=40), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_user_id'), ['user_id'], unique=False)

    op.create_table('avaliacoes_posturais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('cabeca', sa.String(length=255), nullable=True),
    sa.Column('cervical', sa.String(length=255), nullable=True),
    sa.Column('ombros', sa.String(length=255), nullable=True),
    sa.Column('escapulas', sa.String(length=255), nullable=True),
    sa.Column('coluna_toracica', sa.String(length=255), nullable=True),
    sa.Column('lombar', sa.String(length=255), nullable=True),
    sa.Column('quadril', sa.String(length=255), nullable=True),
    sa.Column('joelhos', sa.String(length=255), nullable=True),
    sa.Column('pes', sa.String(length=255), nullable=True),
    sa.Column('alinhamento_frontal', sa.Text(), nullable=True),
    sa.Column('alinhamento_lateral', sa.Text(), nullable=True),
    sa.Column('grau_desvio', sa.String(length=40), nullable=True),
    sa.Column('dor_relatada', sa.String(length=255), nullable=True),
    sa.Column('limitacao_funcional', sa.String(length=255), nullable=True),
    sa.Column('observacoes_tecnicas', sa.Text(), nullable=True),
    sa.Column('observacoes_profissional', sa.Text(), nullable=True),
    sa.Column('img_frontal', sa.String(length=500), nullable=True),
    sa.Column('img_lateral_direita', sa.String(length=500), nullable=True),
    sa.Column('img_lateral_esquerda', sa.String(length=500), nullable=True),
    sa.Column('img_posterior', sa.String(length=500), nullable=True),
    sa.Column('avaliacao_anterior_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['avaliacao_anterior_id'], ['avaliacoes_posturais.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacoes_posturais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_posturais_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_posturais_user_id'), ['user_id'], unique=False)

    op.create_table('protocolos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocolos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocolos_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocolos_user_id'), ['user_id'], unique=False)

    op.create_table('treinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('objetivo', sa.String(length=80), nullable=False),
    sa.Column('modalidade', sa.String(length=60), nullable=False),
    sa.Column('fase', sa.String(length=60), nullable=False),
    sa.Column('divisao', sa.String(length=40), nullable=False),
    sa.Column('frequencia_semanal', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=40), nullable=False),
    sa.Column('protocolo_origem', sa.String(length=80), nullable=True),
    sa.Column('duracao_semanas', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('alerta_medico', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treinos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treinos_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treinos_user_id'), ['user_id'], unique=False)

    op.create_table('exercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treino_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('grupo_muscular', sa.String(length=60), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticoes', sa.String(length=40), nullable=False),
    sa.Column('carga', sa.String(length=40), nullable=True),
    sa.Column('descanso', sa.String(length=40), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('tempo_execucao', sa.String(length=40), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('semana', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tecnica', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['treino_id'], ['treinos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercicios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercicios_treino_id'), ['treino_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercicios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercicios_treino_id'))

    op.drop_table('exercicios')
    with op.batch_alter_table('treinos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treinos_user_id'))
        batch_op.drop_index(batch_op.f('ix_treinos_aluno_id'))

    op.drop_table('treinos')
    with op.batch_alter_table('protocolos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocolos_user_id'))
        batch_op.drop_index(batch_op.f('ix_protocolos_aluno_id'))

    op.drop_table('protocolos')
    with op.batch_alter_table('avaliacoes_posturais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_posturais_user_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_posturais_aluno_id'))

    op.drop_table('avaliacoes_posturais')
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_user_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_data'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_aluno_id'))

    op.drop_table('avaliacoes')
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entries_created_at'))

    op.drop_table('log_entries')
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_user_id'))
        batch_op.drop_index(batch_op.f('ix_alunos_nome'))

    op.drop_table('alunos')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_status'))
        batch_op.drop_index(batch_op.f('ix_ai_analyses_created_at'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
